# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

jobs:
- job: 'mac'
  pool:
    vmImage: 'macos-latest'

  steps:
    - script: |
        cd FaceUnityPlugin/mac && ./release.sh
      displayName: 'Running build script'
    - publish: 'FaceUnityPlugin/mac/build/fu-mac.zip'
      artifact: 'FaceUnityPlugin'
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: 'grelease'
        repositoryName: 'AgoraIO-Community/Agora-Electron-FaceUnity-Plugin'
        assets: '$(System.DefaultWorkingDirectory)/FaceUnityPlugin/mac/build/fu-mac.zip'

- job: 'win'
  pool:
    vmImage: 'vs2015-win2012r2'

  steps:
    - script: |
        cd FaceUnityPlugin/win && ./release.sh
