# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
  - script: |
      wget https://github.com/Faceunity/FULiveDemoMac/releases/download/v6.2.0/FaceUnity-SDK-Mac-v6.2.0.zip -O FaceUnity.zip
    displayName: 'Download FaceUnity'
  - script: |
      unzip -u FaceUnity.zip
      mkdir -p FaceUnityPlugin/FULive
      mv FaceUnity-SDK-Mac FaceUnityPlugin/FULive/mac
    displayName: 'Prepare FaceUnity'
  - script: |
      xcodebuild -project FaceUnityPlugin/mac/FaceUnityPlugin.xcodeproj
    displayName: 'Build Plugin'
  - publish: 'FaceUnityPlugin/mac/build'
    artifact: 'FaceUnityPlugin'
